### ISSUE TITLE
Prepare VirtualBox image

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth#116]
We should prepare a VirtualBox image with:

- PowerAuth 2.0 Server
- PowerAuth 2.0 Admin
- optional default database (MySQL), as a basic testing feature (external DB will be used for production)

**Comment by hvge** [comment]
Just for note, you should go into [OVA images](https://en.wikipedia.org/wiki/Open_Virtualization_Format). That's the industry standard for VM deployment.

**Comment by petrdvorak** [comment]
@hvge Great point!

**Comment by petrdvorak** [comment]
We have Docker images, these are reasonably easy to convert to any virtualization format, by simply using docker in the VM.
