### ISSUE TITLE
Prepare support for security on SOAP service

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth#41]
Currently, the service is not secured by any means. We should allow deployers to enable WS-Security.

http://stackoverflow.com/questions/13512883/how-to-use-encrypted-password-in-wss4j-spring-security
http://blog.krecan.net/2010/06/07/spring-ws-security-on-both-client-and-server/comment-page-1/

**Comment by petr-inmite** [comment]
(Nobody requested this feature so far, so postponing but keeping opened.)

**Comment by petrdvorak** [comment]
As agreed with a customer, using the "username token" authentication will be sufficient for the purpose of inter-application authentication and it will work for both SOAP and REST interface.

http://memorynotfound.com/spring-ws-username-password-authentication-wss4j/

**Comment by petrdvorak** [comment]
It would be great to introduce a new table and new service methods to accommodate these integrations.

**New service methods**

- add method `createIntegrationTokens(name)` that creates a new integration with given name, username and password.
- add method `getIntegrationTokenList` to list all available integration tokens.
- add method `refreshIntegrationTokens(id)` to regenerate username and password for given integration.
- add method `removeIntegrationTokens(id)` to delete given integration.

**New tables**

`pa_integration_tokens (id, name, username, password)`

**New server config**

`powerauth.service.enableSecurity = false`
