### ISSUE TITLE
Make ACTIVATION_ID signed during the activation

### ISSUE THREAD

**Issue by hvge** [lime-company/lime-security-powerauth#53]
In Activation step 11

>  PowerAuth 2.0 Server responds with ACTIVATION_ID, C_KEY_SERVER_PUBLIC...

we can make a little improvement and count with ACTIVATION_ID as a part of signed data. For example: `byte[] C_KEY_SERVER_PUBLIC_SIGNATURE = ECDSA.sign(ACTIVATION_ID  + C_KEY_SERVER_PUBLIC, KEY_SERVER_MASTER_PRIVATE)`

I guess that attacker gets nothing with ACTIVATION_ID tampering, but this change is so cheap and thus why not to do it and also protect the ID.

**Comment by petr-inmite** [comment]
Totally makes sense.

**Comment by petr-inmite** [comment]
This is the current proposed algorithm (to make it work, we need to convert Activation ID to byte[] and introduce a new ByteUtils.concat method, since encrypted public key is a byte[]):

1. PowerAuth 2.0 Server responds with `ACTIVATION_ID`, `C_KEY_SERVER_PUBLIC`, `KEY_EPHEMERAL_PUBLIC` and `C_KEY_SERVER_DATA_SIGNATURE`.

	- `SecretKey KEY_ENCRYPTION_OTP = PBKDF2.expand(ACTIVATION_OTP, ACTIVATION_ID_SHORT.getBytes("UTF-8"), 10 000)`
	- `KeyPair keyPair = KeyGenerator.randomKeyPair()`
	- `PrivateKey KEY_EPHEMERAL_PRIVATE = keyPair.getPrivate()`
	- `PublicKey KEY_EPHEMERAL_PUBLIC = keyPair.getPublic()`
	- `SecretKey EPH_KEY = ECDH.phase(KEY_EPHEMERAL_PRIVATE, KEY_DEVICE_PUBLIC)`
	- `byte[] EPHEMERAL_NONCE = Generator.randomBytes(16)`
	- `byte[] keyPublicBytes = KeyConversion.getBytes(KEY_SERVER_PUBLIC)`
	- **`byte[] C_KEY_SERVER_PUBLIC = AES.encrypt(AES.encrypt(keyPublicBytes, EPHEMERAL_NONCE, KEY_ENCRYPTION_OTP), EPHEMERAL_NONCE, EPH_KEY)`**
	- **`byte[] activationIdBytes = ACTIVATION_ID.getBytes("UTF-8")`**
	- **`byte[] activationData = ByteUtils.concat(activationIdBytes, C_KEY_SERVER_PUBLIC)`**
	- **`byte[] C_KEY_SERVER_DATA_SIGNATURE = ECDSA.sign(activationData, KEY_SERVER_MASTER_PRIVATE)`**

1. PowerAuth 2.0 Client receives an `ACTIVATION_ID`, `C_KEY_SERVER_PUBLIC`, `KEY_EPHEMERAL_PUBLIC` and `C_KEY_SERVER_DATA_SIGNATURE` and if the signature matches the data, it retrieves `KEY_SERVER_PUBLIC`.

	- `SecretKey KEY_ENCRYPTION_OTP = PBKDF2.expand(ACTIVATION_OTP, ACTIVATION_ID_SHORT.getBytes("UTF-8"), 10 000)`
	- **`byte[] activationIdBytes = ACTIVATION_ID.getBytes("UTF-8")`**
	- **`byte[] activationData = ByteUtils.concat(activationIdBytes, C_KEY_SERVER_PUBLIC)`**
	- **`boolean isSignatureOK = ECDSA.verify(activationData, C_KEY_SERVER_DATA_SIGNATURE, KEY_SERVER_MASTER_PRIVATE)`**
	- `SecretKey EPH_KEY = ECDH.phase(KEY_DEVICE_PRIVATE, KEY_EPHEMERAL_PUBLIC)`
	- `byte[] keyPublicBytes = AES.decrypt(AES.decrypt(C_KEY_SERVER_PUBLIC, EPHEMERAL_NONCE, EPH_KEY), EPHEMERAL_NONCE, KEY_ENCRYPTION_OTP)`
	- `PublicKey KEY_SERVER_PUBLIC = KeyConversion.publicKeyFromBytes(keyPublicBytes)`

**Comment by petr-inmite** [comment]
> but this change is so cheap

:) ... an hour later...

**Comment by petr-inmite** [comment]
... also, this change has an impact on the Standard RESTful API - it does not make sense to call the field "encryptedPublicKeySignature" anymore.

@hvge Please come up with changes / consistency fixes like this as soon as possible - these "cheap changes" usually have broad consequences...
