### ISSUE TITLE
Make Spring integration smoother with a custom @PowerAuth annotation

### ISSUE THREAD

**Issue by petr-inmite** [lime-company/lime-security-powerauth#72]
We would like to simplify the work the developer who wants to integrate with PowerAuth 2.0 has to do.

Principle:

- Remove the need for autowired authentication provider
- Replace the signature verification call with a custom request filter
- Bind the request filter to a custom annotation with parameters
- Inject the resulting authentication object in a method parameter

See this StackOverflow question:

http://stackoverflow.com/questions/36887109/adding-custom-spring-security-filter-on-controller-method-using-annotation

Current code:

```java
@Controller
@RequestMapping(value = "/session")
public class AuthenticationController {

    @Autowired
    private PowerAuthAuthenticationProvider authenticationProvider;

    @RequestMapping(value = "/login", method = RequestMethod.POST)
    public @ResponseBody String login(
            @RequestHeader(value = "X-PowerAuth-Authorization", required = true) String signatureHeader,
            HttpServletRequest servletRequest) throws Exception {

        PowerAuthApiAuthentication apiAuthentication = authenticationProvider.validateRequestSignature(
                servletRequest,
                "/session/login",
                signatureHeader
        );

        if (apiAuthentication != null && apiAuthentication.getUserId() != null) {
            return "OK";
        } else {
            return "NOT OK";
        }
    }
}
```

Proposed code:

```java
@Controller
@RequestMapping(value = "/session")
public class AuthenticationController {

    @RequestMapping(value = "/login", method = RequestMethod.POST)
    @PowerAuth(value = "/session/login")
    public @ResponseBody String login(PowerAuthApiAuthentication apiAuthentication) throws Exception {
        if (apiAuthentication != null && apiAuthentication.getUserId() != null) {
            return "OK";
        } else {
            return "NOT OK";
        }
    }
}
```

**Comment by novoj** [comment]
You may use custom implementation of org.springframework.web.bind.support.WebArgumentResolver interface. More details can be found in this article: https://sergialmar.wordpress.com/2011/03/29/extending-handler-method-argument-resolution-in-spring-mvc/

But if the condition `apiAuthentication != null && apiAuthentication.getUserId() != null` is static (ie. you always want to check this and thus PowerAuthApiAuthentication method argument is not required in most cases you may then use own org.springframework.web.servlet.handler.HandlerInterceptorAdapter implementation:

Client code example:

``` java
@Controller
@RequestMapping(value = "/session")
public class AuthenticationController {

    @RequestMapping(value = "/login", method = RequestMethod.POST)
    @PowerAuth(value = "/session/login")
    public @ResponseBody String login() throws Exception {
          return "OK"
    }
}
```

How to implement HandlerInterceptor tutorial: http://viralpatel.net/blogs/spring-mvc-interceptor-example/

But you can use this approach only when the negotiation logic is always the same for all methods.

If you need further assistance - feel free to contact me.

**Comment by novoj** [comment]
Btw. as a client I'd like to get rid also of "/session/login" argument if it is computable from @RequestMappings :)

**Comment by petr-inmite** [comment]
Thank you, I will have a look at the resources. :)

The if condition may be dynamic or not present at all - the point is that in the method body, developer may need to work with `userId` (for example, return accounts for given user) and it's good practice to check for null, IMO. I shouldn't have put it in the example. I think we could get rid of the "authentication != null" part though, and inject the authentication in a method parameter (and throw exception we already have there when authentication fails, for example).

About that extra "/session/login" attribute - this is an "endpoint identifier" and it may be different from endpoint URL. It was introduced in PowerAuth because the API application may run on different endpoints from the client and server perspective (for example, client may call "https://api.service.com/endpoint/payment" while server runs internally on "https://intws:8765/mb/a/b/c/d/payment") and we needed a way to uniquelly identify endpoints (client and server must agree on shared constants, that are by convention the same as the "key portion of endpoint path" but may be anything).

**Comment by novoj** [comment]
I see.

I'd recommend to get rid of Null check if it ultimately means auth. fail - you may do that in HandlerInterceptor.

I understand the need of mapping external URLs on internal ones - but when it's due to some proxy mechanism the original URI is usually propagated in some HTTP header. So maybe there's still chance to acquire the value automatically?

**Comment by novoj** [comment]
Since PowerAuth is opensource, I could help you with implementation if you need and will provide me with same test-case.

**Comment by petr-inmite** [comment]
I will have a look (this Friday) and if I get stuck, I will be dropping you a line... :)

**Comment by petr-inmite** [comment]
@novoj Ahoj, hodíš mi na to prosím code-review očko? :) b066baf4346e0709a8a8b67270721e7f44923087

**Comment by novoj** [comment]
Seems ok to me - I don't see the big picture, but cogwheels seems to ok :)

I would avoid using System.out.println in the code and would include some integration tests (but they might be there already and weren't only included in commit). Nice and compherensible code is it.

**Comment by petr-inmite** [comment]
Thank you, mainly for pointing out that "System.out" - I don't use it and here it was just for a super quick debugging and forgot to remove. :-/ Integration tests are on the checklist, I need to improve unit tests first.
