### ISSUE TITLE
Replace hardcoded constant values in code by constants

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth#82]
The code currently uses a lot of harmless hardcoded string constants, such as "UTF-8", "BC", "SC", "AES/ECB/NoPadding", "AES/CBC/PKCS7Padding", "PBKDF2WithHmacSHA1", "EC", "ECDH", "secp256r1", "HmacSHA256", "SHA-256", etc.

It would be nice to extract these in a single file as constants.

**Comment by petr-inmite** [comment]
KeyGenerator.java a možná i jiné soubory obsahují hardcoded také délky klíčů, např 16 nebo 128. I toto bychom měli extrahovat do konstant.

**Comment by petrdvorak** [comment]
This change is practically not need by anyone.
